[package]
name = "benchmark"
version = "0.1.0"
authors = ["Félix Poulin-Bélanger <f.poulinbelanger@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
tokio = { version = "1", features = ["full"] }
